jenkinsci/forensics-api-plugin

pom.xml
src/main/java/io/jenkins/plugins/forensics/blame/FileBlame.java
src/test/java/io/jenkins/plugins/forensics/blame/BlamesTest.java
src/test/java/io/jenkins/plugins/forensics/blame/FileBlameTest.java

See [JENKINS-60014](https://issues.jenkins-ci.org/browse/JENKINS-60014).
Introduce the time of a commit to the blame. This enables the user to see not only who made a change, but also when the change was made.

[JENKINS-60014] Add the time of a commit to the blame.

---

src/main/java/io/jenkins/plugins/forensics/miner/FileStatistics.java
src/test/java/io/jenkins/plugins/forensics/miner/FileStatisticsTest.java

See [JENKINS-60048](https://issues.jenkins-ci.org/browse/JENKINS-60048).
This exposes the absolute time of creation and modification of a file in the `FileStatistics`.

[JENKINS-60048] Add absolute creation and modification times to statistics API.

---

pom.xml

This should help plugins.jenkins.io display the documentation correctly in https://plugins.jenkins.io/forensics-api
Not using Maven properties because they are currently not expanded properly (https://github.com/jenkins-infra/update-center2/pull/303)

Add documentation URL (GitHub)

---

src/main/java/io/jenkins/plugins/forensics/blame/BlamerFactory.java
src/main/java/io/jenkins/plugins/forensics/miner/MinerFactory.java
src/test/java/io/jenkins/plugins/forensics/blame/BlamerFactoryITest.java
src/test/java/io/jenkins/plugins/forensics/miner/MinerFactoryITest.java

Currently nothing is reported in the console log if the blamer or miner cannot be created. 
Now error messages are logged if the `git-forensics` plugin is not installed or if the logger cannot be created.

Improve logging if miner or BlamerFactory cannot be created

---

Jenkinsfile

Updated to follow what is in the buildPlugin.groovy from the global pipeline library.
Is there a reason that you aren't using buildPlugin() directly? Maybe something we could implement in the global library so we can keep a single source of buildPlugin?

Update to similar usage as global library buildPlugin

---

src/main/java/io/jenkins/plugins/forensics/reference/ReferenceFinder.java
src/test/java/io/jenkins/plugins/forensics/reference/ReferenceFinderTest.java

This new cass provides consumers a simple API to obtain a reference build.

Add a small wrapper around ReferenceBuild

---

src/main/java/io/jenkins/plugins/forensics/miner/MinerService.java
src/test/java/io/jenkins/plugins/forensics/miner/MinerServiceTest.java

Add a new `MinerService` that can query for specific repository statistics that are stored in an associated ForensicsBuildAction.

Add a consumer API for the miner

---

src/main/java/io/jenkins/plugins/forensics/reference/ReferenceJobModelValidation.java
src/main/java/io/jenkins/plugins/forensics/reference/ReferenceRecorder.java
src/main/java/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorder.java
src/main/resources/io/jenkins/plugins/forensics/reference/Messages.properties
src/main/resources/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorder/config.jelly
src/main/resources/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorder/config.properties
src/main/resources/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorder/help-referenceJob.html
src/test/java/io/jenkins/plugins/forensics/reference/ReferenceJobModelValidationTest.java
src/test/java/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorderITest.java

Create a `SimpleReferenceRecorder` that can be used if the `GitReferenceRecorder` does not work. Otherwise the warnings plugin will not be able to obtain a reference build.

Add a fallback reference recorder

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorder.java
src/main/resources/io/jenkins/plugins/forensics/miner/ForensicsBuildAction/summary.jelly
src/main/resources/io/jenkins/plugins/forensics/miner/Messages.properties
src/main/resources/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorder/config.jelly
src/test/java/io/jenkins/plugins/forensics/ArchitectureTest.java

Downstream PR of jenkinsci/plugin-util-api-plugin#66. 
Use `@POST` for field validation. For details see https://www.jenkins.io/doc/developer/security/form-validation/.

Use @POST for form field validation

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/blame/BlamerFactory.java
src/main/java/io/jenkins/plugins/forensics/miner/AbstractForensicsAction.java
src/main/java/io/jenkins/plugins/forensics/miner/ForensicsBuildAction.java
src/main/java/io/jenkins/plugins/forensics/miner/ForensicsCodeMetricAction.java
src/main/java/io/jenkins/plugins/forensics/miner/ForensicsJobAction.java
src/main/java/io/jenkins/plugins/forensics/miner/ForensicsViewModel.java
src/main/java/io/jenkins/plugins/forensics/miner/MinerFactory.java
src/main/java/io/jenkins/plugins/forensics/miner/MinerService.java
src/main/java/io/jenkins/plugins/forensics/miner/RepositoryMinerStep.java
src/main/java/io/jenkins/plugins/forensics/reference/ReferenceRecorder.java
src/main/java/io/jenkins/plugins/forensics/reference/package-info.java
src/main/java/io/jenkins/plugins/forensics/util/CommitDecoratorFactory.java
src/main/java/io/jenkins/plugins/forensics/util/ScmResolver.java
src/main/resources/forensics/scm.jelly
src/main/resources/forensics/scm.properties
src/main/resources/io/jenkins/plugins/forensics/miner/ForensicsBuildAction/summary.jelly
src/main/resources/io/jenkins/plugins/forensics/miner/ForensicsBuildAction/summary.properties
src/main/resources/io/jenkins/plugins/forensics/miner/Messages.properties
src/main/resources/io/jenkins/plugins/forensics/miner/RepositoryMinerStep/config.jelly
src/test/java/io/jenkins/plugins/forensics/miner/MinerServiceTest.java
src/test/java/io/jenkins/plugins/forensics/util/ScmResolverTest.java

Some jobs are using multiple SCM repositories: one for the code, one for the pipeline library, etc. We need a way to select the correct repository for all features of the forensics API. See also [JENKINS-64578](https://issues.jenkins.io/browse/JENKINS-64578).
See downstream PR https://github.com/jenkinsci/git-forensics-plugin/pull/213

[JENKINS-64578] Support multiple SCM repositories per job

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/reference/ReferenceRecorder.java

Replace the fragile job name computation based on the branch name: reuse branch API to obtain the correct job for a given branch. See [JENKINS-64544](https://issues.jenkins.io/browse/JENKINS-64544).

Make use of branch API to obtain correct reference job.

---

src/main/java/io/jenkins/plugins/forensics/miner/RepositoryMinerStep.java

```
ERROR: Build step failed with exception
java.lang.NullPointerException
at java.lang.String.contains(String.java:2133)
at io.jenkins.plugins.forensics.util.ScmResolver.lambda$getScms$0(ScmResolver.java:59)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
at …
```

Fix NPE if SCM key is `null` in old serialization

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/miner/CommitStatisticsBuildAction.java
src/main/resources/io/jenkins/plugins/forensics/miner/CommitStatisticsBuildAction/summary.jelly

If the reference build has been found then both decision paths have been rendered.

Fix the link to the reference build

---

src/main/java/io/jenkins/plugins/forensics/miner/CommitStatistics.java
src/main/java/io/jenkins/plugins/forensics/reference/ReferenceFinder.java
src/test/java/io/jenkins/plugins/forensics/miner/CommitStatisticsTest.java

Make logging output consistent across the different steps.

Use upper-case for logging statements

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/miner/FileDetailsView.java
src/main/java/io/jenkins/plugins/forensics/util/CommitDecorator.java
src/main/resources/io/jenkins/plugins/forensics/miner/FileDetailsView/index.jelly

If a repository browser has been configured then the corresponding link is opened.

Open commit repository URL on click in trend chart

---

src/test/java/io/jenkins/plugins/forensics/miner/AddedVersusDeletedLinesForensicsSeriesBuilderTest.java

A first test for `AddedVersusDeletedLinesForensicsSeriesBuilder` that uses Mockito

A first test for `AddedVersusDeletedLinesForensicsSeriesBuilder`

---

src/test/java/io/jenkins/plugins/forensics/miner/CodeMetricTrendChartTest.java

Added Test for class CodeMetricTrendChart.java
JENKINS-66867

Add unit test for `CodeMetricTrendChart`

---

src/test/java/io/jenkins/plugins/forensics/miner/AddedVersusDeletedLinesTrendChartTest.java

Add unit test for `AddedVersusDeletedLinesTrendChart`

---

src/test/java/io/jenkins/plugins/forensics/miner/RelativeCountTrendChartTest.java

Added Test for class RelativeCountTrendChart.java
JENKINS-66866

Add test for `RelativeCountTrendChartTest`

---

src/main/java/io/jenkins/plugins/forensics/reference/ReferenceRecorder.java
src/test/java/io/jenkins/plugins/forensics/reference/ReferenceRecorderTest.java

The initial value of the `targetBranch` (previously called `defaultBranch`) should be empty. Otherwise it will take precedence over the automatic branch discovery.

The initial setting of default branch should be empty

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/reference/ReferenceBuild.java
src/main/java/io/jenkins/plugins/forensics/reference/ReferenceRecorder.java
src/main/resources/io/jenkins/plugins/forensics/reference/Messages.properties
src/main/resources/io/jenkins/plugins/forensics/reference/ReferenceBuild/summary.jelly
src/main/resources/io/jenkins/plugins/forensics/reference/ReferenceBuild/summary.properties
src/test/java/io/jenkins/plugins/forensics/reference/ReferenceBuildTest.java

This view has been copied from the warnings-ng plugin and is now available for all plugins that want to show information and error messages. This is a downstream PR for jenkinsci/bootstrap5-api-plugin#65.

Add a new detail view that shows info and error messages

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/delta/DeltaCalculator.java
src/main/java/io/jenkins/plugins/forensics/delta/DeltaCalculatorFactory.java
src/main/java/io/jenkins/plugins/forensics/delta/model/Change.java
src/main/java/io/jenkins/plugins/forensics/delta/model/ChangeEditType.java
src/main/java/io/jenkins/plugins/forensics/delta/model/Delta.java
src/main/java/io/jenkins/plugins/forensics/delta/model/FileChanges.java
src/main/java/io/jenkins/plugins/forensics/delta/model/FileEditType.java
src/main/java/io/jenkins/plugins/forensics/delta/model/package-info.java
src/main/java/io/jenkins/plugins/forensics/delta/package-info.java
src/test/java/io/jenkins/plugins/forensics/delta/DeltaCalculatorFactoryITest.java
src/test/java/io/jenkins/plugins/forensics/delta/model/ChangeTest.java
src/test/java/io/jenkins/plugins/forensics/delta/model/DeltaTest.java
src/test/java/io/jenkins/plugins/forensics/delta/model/FileChangesTest.java
src/test/resources/design.puml

An API which calculates the code differences - so called 'delta' - between two commits.
The resulting delta model contains information about:
- which files have been changed in which way
- which concrete lines within these files have been changed in which way
The implementation for Git is available in the downstream PR jenkinsci/git-forensics-plugin#390

Add Code Difference API

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/delta/model/Change.java
src/test/java/io/jenkins/plugins/forensics/delta/model/ChangeTest.java

I expanded the code delta API that it also provides the affected lines, which will be changed by a new commit, as they were before the change has been made.

Provide affected lines for code delta

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/delta/DeltaCalculator.java
src/test/java/io/jenkins/plugins/forensics/delta/DeltaCalculatorFactoryITest.java

I adjusted the code delta API so that the delta is calculated dependent on a passed SCM key filter in case that multiple SCMs are in use.

Choose SCM when calculating the code delta

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/delta/model/FileChanges.java
src/test/java/io/jenkins/plugins/forensics/delta/model/FileChangesTest.java

I added an attribute to `FileChanges` in order to store the file path before a rename.

Store old file name for processing file renames

---

pom.xml
src/main/resources/io/jenkins/plugins/forensics/miner/CommitStatisticsBuildAction/summary.jelly
src/main/resources/io/jenkins/plugins/forensics/miner/ForensicsBuildAction/summary.jelly

Use the `hashCode` of SCM as ID to avoid illegal characters in ID.

Use hashCode as `ID`

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/miner/AddedVersusDeletedLinesTrendChart.java
src/main/java/io/jenkins/plugins/forensics/miner/CodeMetricTrendChart.java
src/main/java/io/jenkins/plugins/forensics/miner/FileDetailsView.java
src/main/java/io/jenkins/plugins/forensics/miner/FilesCountTrendChart.java
src/main/java/io/jenkins/plugins/forensics/miner/RelativeCountTrendChart.java
src/main/java/io/jenkins/plugins/forensics/miner/SizePieChart.java
src/test/java/io/jenkins/plugins/forensics/miner/FilesCountTrendChartTest.java

Use colors from the new Echarts `JenkinsPalette` for trend charts.
Downstream PR of https://github.com/jenkinsci/echarts-api-plugin/pull/287.

Make trend charts theme-aware

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/delta/Change.java
src/main/java/io/jenkins/plugins/forensics/delta/Delta.java
src/main/java/io/jenkins/plugins/forensics/delta/DeltaCalculator.java
src/main/java/io/jenkins/plugins/forensics/delta/FileChanges.java
src/main/java/io/jenkins/plugins/forensics/miner/RelativeCountTrendChart.java
src/test/java/io/jenkins/plugins/forensics/delta/DeltaCalculatorFactoryITest.java
src/test/java/io/jenkins/plugins/forensics/delta/DeltaTest.java
src/test/java/io/jenkins/plugins/forensics/delta/FileChangesTest.java
src/test/java/io/jenkins/plugins/forensics/miner/AddedVersusDeletedLinesForensicsSeriesBuilderTest.java
src/test/java/io/jenkins/plugins/forensics/miner/CodeMetricSeriesBuilderTest.java
src/test/java/io/jenkins/plugins/forensics/miner/CommitStatisticsTest.java
src/test/java/io/jenkins/plugins/forensics/miner/ForensicsTableModelTest.java
src/test/java/io/jenkins/plugins/forensics/miner/RelativeCountTrendChartTest.java
src/test/java/io/jenkins/plugins/forensics/miner/SizePieChartTest.java

Required for the warnings plugin, to visualize the issues in modified code.

Add method to compute all the modified lines of a file change

---

src/main/java/io/jenkins/plugins/forensics/reference/ReferenceJobModelValidation.java
src/main/java/io/jenkins/plugins/forensics/reference/ReferenceRecorder.java
src/main/java/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorder.java
src/main/resources/io/jenkins/plugins/forensics/miner/RepositoryMinerStep/help-scm.html
src/main/resources/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorder/config.jelly
src/main/resources/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorder/config.properties
src/main/resources/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorder/help-considerRunningBuild.html
src/test/java/io/jenkins/plugins/forensics/reference/ReferenceRecorderTest.java
src/test/java/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorderTest.java

In some rare cases it might make sense to select a reference build that is not yet complete. In those cases the pipeline must ensure that the required build results are already available.
See [JENKINS-73380](https://issues.jenkins.io/browse/JENKINS-73380).

[JENKINS-73380] Add option to consider running builds as reference

---

src/main/java/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorder.java
src/test/java/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorderITest.java

Otherwise, there will be multiple reference build actions, but there must be only one that identifies the baseline. Log an error message if the action already exists since the baseline should be constant.
See [JENKINS-73380](https://issues.jenkins.io/browse/JENKINS-73380).

[JENKINS-73380] Make sure that any existing reference build action is removed

---

src/main/java/io/jenkins/plugins/forensics/util/ScmResolver.java
src/test/java/io/jenkins/plugins/forensics/util/ScmResolverTest.java

Improve the selection of the correct SCM (see [JENKINS-75429](https://issues.jenkins.io/browse/JENKINS-75429)). It makes sense to ignore the capitalization of the name as it is not relevant on Windows.
Supersedes #587

[JENKINS-75429] Ignore the case of the SCM when matching the SCM repository parameter

---

pom.xml
src/test/java/io/jenkins/plugins/archunit/PluginArchitectureTest.java

Bump the version of plugin-util to 6.1165.v322e76215b_a_4. This version contains the missing class again.

[JENKINS-76020] Resolve missing architecture rules
