jenkinsci/forensics-api-plugin

pom.xml

See https://issues.jenkins-ci.org/browse/JENKINS-60182

[JENKINS-60182] Move Eclipse collections to test dependencies

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorder.java
src/test/java/io/jenkins/plugins/forensics/PluginArchitectureTest.java

- Check for @POST
- Add permission checks

Improve security for `doFill` methods.

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorder.java

Downstream PR for https://github.com/jenkinsci/plugin-util-api-plugin/pull/68.

Also check for permissions in `check` methods

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/miner/MinerService.java
src/test/java/io/jenkins/plugins/forensics/miner/MinerServiceTest.java

Add missing result of service call.

Improve logging of mining service

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/miner/ForensicsBuildAction.java

Otherwise the sidebar menu will get too wide.

Remove repository key from action name

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorder.java

See [JENKINS-64627](https://issues.jenkins.io/browse/JENKINS-64627) for details.

[JENKINS-64627] Use CONFIGURE permission of specific job if possible

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/miner/FileStatistics.java
src/main/java/io/jenkins/plugins/forensics/miner/ForensicsBuildAction.java
src/main/java/io/jenkins/plugins/forensics/miner/ForensicsCodeMetricAction.java
src/main/java/io/jenkins/plugins/forensics/miner/ForensicsJobAction.java
src/main/java/io/jenkins/plugins/forensics/miner/MinerFactory.java
src/main/java/io/jenkins/plugins/forensics/miner/MinerService.java
src/main/java/io/jenkins/plugins/forensics/miner/RepositoryMiner.java
src/main/java/io/jenkins/plugins/forensics/miner/RepositoryMinerStep.java
src/main/java/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorder.java
src/main/java/io/jenkins/plugins/forensics/util/CommitDecoratorFactory.java
src/main/resources/io/jenkins/plugins/forensics/miner/FileDetailsView/index.jelly
src/test/java/io/jenkins/plugins/forensics/blame/BlamesXmlStreamTest.java
src/test/java/io/jenkins/plugins/forensics/miner/MinerFactoryITest.java
src/test/java/io/jenkins/plugins/forensics/miner/RepositoryStatisticsXmlStreamTest.java

Requires new Jenkins Baseline 2.249.1

Bump version of analysis-pom to to 5.0.0

---

src/main/java/io/jenkins/plugins/forensics/miner/ForensicsTableModel.java

Full path is shown as tooltip only.

Show simple file name in file column

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/miner/AddedVersusDeletedLinesCommitStatisticsSeriesBuilder.java
src/main/java/io/jenkins/plugins/forensics/miner/AddedVersusDeletedLinesForensicsSeriesBuilder.java
src/main/java/io/jenkins/plugins/forensics/miner/AddedVersusDeletedLinesTrendChart.java
src/main/java/io/jenkins/plugins/forensics/miner/CommitStatisticsBuildAction.java
src/main/java/io/jenkins/plugins/forensics/miner/CommitStatisticsJobAction.java
src/main/java/io/jenkins/plugins/forensics/miner/ForensicsJobAction.java
src/main/java/io/jenkins/plugins/forensics/miner/RelativeCountCommitStatisticsSeriesBuilder.java
src/main/java/io/jenkins/plugins/forensics/miner/RelativeCountForesnsicsSeriesBuilder.java
src/main/java/io/jenkins/plugins/forensics/miner/RelativeCountTrendChart.java
src/main/resources/io/jenkins/plugins/forensics/miner/CommitStatisticsJobAction/floatingBox.jelly
src/main/resources/io/jenkins/plugins/forensics/miner/ForensicsJobAction/floatingBox.jelly

Reuse the trend charts of the forensics miner for the commit statistics action.

A trend charts for the commit statistics

---

src/main/java/io/jenkins/plugins/forensics/miner/CodeMetricSeriesBuilder.java
src/main/java/io/jenkins/plugins/forensics/miner/FileDetailsView.java

The ID was a localized string which could be changed by users.

Use constant strings for chart series IDs

---

src/main/java/io/jenkins/plugins/forensics/reference/ReferenceBuild.java

Other plugins might be interested in rendering a link rather than the plain text of the build ID.

Add an API to obtain a reference build link

---

src/main/java/io/jenkins/plugins/forensics/reference/ReferenceRecorder.java
src/test/java/io/jenkins/plugins/forensics/miner/CodeMetricTrendChartTest.java
src/test/java/io/jenkins/plugins/forensics/reference/ReferenceRecorderTest.java

Otherwise, overriding sub-classes have no chance to report the progress.

Improve API by providing an additional logger in `find`.

---

src/test/java/io/jenkins/plugins/forensics/miner/CommitStatisticsJobActionTest.java

https://issues.jenkins.io/browse/JENKINS-66878

[JENKINS-66878] Unit test for CommitStatisticsJobAction

---

.github/workflows/ci.yml
src/main/resources/io/jenkins/plugins/forensics/reference/ReferenceBuild/summary.jelly

Some icons have been renamed in FontAwesome 6.x.

Fix icon names for FontAwesome 6.x.

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/delta/DeltaCalculator.java
src/test/java/io/jenkins/plugins/forensics/delta/DeltaCalculatorFactoryITest.java

I expanded the API for calculating the code delta with another method which calculates the delta between two Jenkins builds.

Expanded code delta API

---

pom.xml
src/main/resources/index.jelly
src/test/java/io/jenkins/plugins/forensics/PluginArchitectureTest.java
src/test/java/io/jenkins/plugins/forensics/blame/BlamerFactoryITest.java
src/test/java/io/jenkins/plugins/forensics/delta/DeltaCalculatorFactoryITest.java
src/test/java/io/jenkins/plugins/forensics/miner/MinerFactoryITest.java
src/test/java/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorderITest.java

Downstream PR of jenkinsci/plugin-util-api-plugin#161.

Use JUnit 5 for integration tests

---

src/main/resources/io/jenkins/plugins/forensics/miner/CommitStatisticsBuildAction/summary.jelly
src/main/resources/io/jenkins/plugins/forensics/miner/ForensicsBuildAction/summary.jelly
src/main/resources/io/jenkins/plugins/forensics/reference/ReferenceBuild/summary.jelly

This will simplify selection of those summaries in UI tests.

Add IDs around the build `summary.jelly` content

---

src/test/java/io/jenkins/plugins/forensics/miner/CodeMetricSeriesBuilderTest.java

**The issue**
You can find all the issue details [here](https://issues.jenkins.io/browse/JENKINS-66861).
**My updates:**
I've created the test for the `CodeMetricSeriesBuilder` class.

[JENKINS-66861] Add test for `CodeMetricSeriesBuilder`

---

pom.xml

Use BOM version for ECharts

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/coverage.yml
src/main/resources/io/jenkins/plugins/forensics/miner/CommitStatisticsJobAction/configure-trend.js
src/main/resources/io/jenkins/plugins/forensics/miner/CommitStatisticsJobAction/floatingBox.jelly
src/main/resources/io/jenkins/plugins/forensics/miner/FileDetailsView/index.jelly
src/main/resources/io/jenkins/plugins/forensics/miner/FileDetailsView/render-trend.js
src/main/resources/io/jenkins/plugins/forensics/miner/ForensicsJobAction/configure-trend.js
src/main/resources/io/jenkins/plugins/forensics/miner/ForensicsJobAction/floatingBox.jelly

See [JENKINS-71014](https://issues.jenkins.io/browse/JENKINS-71014) for details.

CSP: Extract inline JS into an adjunct

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/coverage.yml
.github/workflows/quality-monitor.yml

Enable quality monitor

---

pom.xml
src/main/java/io/jenkins/plugins/forensics/miner/ForensicsViewModel.java
src/main/java/io/jenkins/plugins/forensics/reference/ReferenceRecorder.java
src/main/java/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorder.java
src/test/java/io/jenkins/plugins/forensics/miner/ForensicsViewModelTest.java
src/test/java/io/jenkins/plugins/forensics/reference/SimpleReferenceRecorderITest.java

Replace deprecated methods with non-deprecated equivalents.

Migrate from EE 8 to EE 9
